/**
 * @packageDocumentation
 * @module api.functional.project.colors
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

/**
 * @controller ProjectsController.getColors
 * @path GET /project/colors
 * @accessor api.functional.project.colors.getColors
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getColors(
  connection: IConnection,
): Promise<getColors.Output> {
  return PlainFetcher.fetch(connection, {
    ...getColors.METADATA,
    template: getColors.METADATA.path,
    path: getColors.path(),
  });
}
export namespace getColors {
  export type Output = {
    id: string;
    hexCode: string;
    placement: number;
    projects: {
      id: string;
      name: null | string;
    }[];
  }[];

  export const METADATA = {
    method: "GET",
    path: "/project/colors",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/project/colors";
}
