/**
 * @packageDocumentation
 * @module api.functional.time_component
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { CreateTimeComponentDto } from "../../structures/CreateTimeComponentDto";
import type { Prisma } from "../../structures/Prisma";
import type { UpdateTimeComponentDto } from "../../structures/UpdateTimeComponentDto";

/**
 * @controller TimeComponentsController.getTimeComponentsByUser
 * @path GET /time-component
 * @accessor api.functional.time_component.getTimeComponentsByUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getTimeComponentsByUser(
  connection: IConnection,
): Promise<getTimeComponentsByUser.Output> {
  return PlainFetcher.fetch(connection, {
    ...getTimeComponentsByUser.METADATA,
    template: getTimeComponentsByUser.METADATA.path,
    path: getTimeComponentsByUser.path(),
  });
}
export namespace getTimeComponentsByUser {
  export type Output = Prisma.PrismaPromiseArray__type.o1;

  export const METADATA = {
    method: "GET",
    path: "/time-component",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/time-component";
}

/**
 * @controller TimeComponentsController.createTimeComponent
 * @path POST /time-component
 * @accessor api.functional.time_component.createTimeComponent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createTimeComponent(
  connection: IConnection,
  body: createTimeComponent.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createTimeComponent.METADATA,
      template: createTimeComponent.METADATA.path,
      path: createTimeComponent.path(),
    },
    body,
  );
}
export namespace createTimeComponent {
  export type Body = CreateTimeComponentDto;

  export const METADATA = {
    method: "POST",
    path: "/time-component",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/time-component";
}

/**
 * @controller TimeComponentsController.updateTimeComponent
 * @path PATCH /time-component
 * @accessor api.functional.time_component.updateTimeComponent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateTimeComponent(
  connection: IConnection,
  body: updateTimeComponent.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateTimeComponent.METADATA,
      template: updateTimeComponent.METADATA.path,
      path: updateTimeComponent.path(),
    },
    body,
  );
}
export namespace updateTimeComponent {
  export type Body = UpdateTimeComponentDto;

  export const METADATA = {
    method: "PATCH",
    path: "/time-component",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/time-component";
}

/**
 * @controller TimeComponentsController.deleteTimeComponent
 * @path DELETE /time-component
 * @accessor api.functional.time_component.deleteTimeComponent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteTimeComponent(
  connection: IConnection,
  query: deleteTimeComponent.Query,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteTimeComponent.METADATA,
    template: deleteTimeComponent.METADATA.path,
    path: deleteTimeComponent.path(query),
  });
}
export namespace deleteTimeComponent {
  export type Query = {
    id: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/time-component",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/time-component";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
