/**
 * @packageDocumentation
 * @module api.functional.recurring_time_component
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { CreateRecurringTimeComponentDto } from "../../structures/CreateRecurringTimeComponentDto";
import type { UpdateRecurringTimeComponentDto } from "../../structures/UpdateRecurringTimeComponentDto";

/**
 * @controller RecurringTimeComponentsController.getRecurringTimeComponentsByUser
 * @path GET /recurring-time-component
 * @accessor api.functional.recurring_time_component.getRecurringTimeComponentsByUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getRecurringTimeComponentsByUser(
  connection: IConnection,
): Promise<getRecurringTimeComponentsByUser.Output> {
  return PlainFetcher.fetch(connection, {
    ...getRecurringTimeComponentsByUser.METADATA,
    template: getRecurringTimeComponentsByUser.METADATA.path,
    path: getRecurringTimeComponentsByUser.path(),
  });
}
export namespace getRecurringTimeComponentsByUser {
  export type Output = {
    id: string;
    recurringInterval: number;
    recurringFrequency: "DAY" | "WEEK" | "MONTH" | "YEAR";
    recurringByDay: ("MO" | "TU" | "WE" | "TH" | "FR" | "SA" | "SU")[];
    recurringByMonthDay: null | number;
    recurringByMonth: null | number;
    firstRecurringEventAt: string & tags.Format<"date-time">;
    lastRecurringEventAt: null | (string & tags.Format<"date-time">);
    projectId: string;
  }[];

  export const METADATA = {
    method: "GET",
    path: "/recurring-time-component",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/recurring-time-component";
}

/**
 * @controller RecurringTimeComponentsController.createRecurringTimeComponent
 * @path POST /recurring-time-component
 * @accessor api.functional.recurring_time_component.createRecurringTimeComponent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createRecurringTimeComponent(
  connection: IConnection,
  body: createRecurringTimeComponent.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createRecurringTimeComponent.METADATA,
      template: createRecurringTimeComponent.METADATA.path,
      path: createRecurringTimeComponent.path(),
    },
    body,
  );
}
export namespace createRecurringTimeComponent {
  export type Body = CreateRecurringTimeComponentDto;

  export const METADATA = {
    method: "POST",
    path: "/recurring-time-component",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/recurring-time-component";
}

/**
 * @controller RecurringTimeComponentsController.updateRecurringTimeComponent
 * @path PATCH /recurring-time-component
 * @accessor api.functional.recurring_time_component.updateRecurringTimeComponent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateRecurringTimeComponent(
  connection: IConnection,
  body: updateRecurringTimeComponent.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateRecurringTimeComponent.METADATA,
      template: updateRecurringTimeComponent.METADATA.path,
      path: updateRecurringTimeComponent.path(),
    },
    body,
  );
}
export namespace updateRecurringTimeComponent {
  export type Body = UpdateRecurringTimeComponentDto;

  export const METADATA = {
    method: "PATCH",
    path: "/recurring-time-component",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/recurring-time-component";
}

/**
 * @controller RecurringTimeComponentsController.deleteRecurringTimeComponent
 * @path DELETE /recurring-time-component
 * @accessor api.functional.recurring_time_component.deleteRecurringTimeComponent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteRecurringTimeComponent(
  connection: IConnection,
  query: deleteRecurringTimeComponent.Query,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteRecurringTimeComponent.METADATA,
    template: deleteRecurringTimeComponent.METADATA.path,
    path: deleteRecurringTimeComponent.path(query),
  });
}
export namespace deleteRecurringTimeComponent {
  export type Query = {
    id: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/recurring-time-component",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/recurring-time-component";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
