/**
 * @packageDocumentation
 * @module api.functional.auth.refresh_token
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

/**
 * @controller AuthController.refreshToken
 * @path POST /auth/refresh-token
 * @accessor api.functional.auth.refresh_token.refreshToken
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function refreshToken(
  connection: IConnection,
): Promise<refreshToken.Output> {
  return PlainFetcher.fetch(connection, {
    ...refreshToken.METADATA,
    template: refreshToken.METADATA.path,
    path: refreshToken.path(),
  });
}
export namespace refreshToken {
  export type Output = {
    accessToken: `${string}-${string}-${string}-${string}-${string}`;
    refreshToken: `${string}-${string}-${string}-${string}-${string}`;
  };

  export const METADATA = {
    method: "POST",
    path: "/auth/refresh-token",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/auth/refresh-token";
}
