/**
 * @packageDocumentation
 * @module api.functional.timezone_change
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { CreateTimezoneChangeDto } from "../../structures/CreateTimezoneChangeDto";
import type { UpdateTimezoneChangeDto } from "../../structures/UpdateTimezoneChangeDto";

/**
 * @controller TimezoneChangeController.getUserTimezoneChanges
 * @path GET /timezone-change
 * @accessor api.functional.timezone_change.getUserTimezoneChanges
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getUserTimezoneChanges(
  connection: IConnection,
): Promise<getUserTimezoneChanges.Output> {
  return PlainFetcher.fetch(connection, {
    ...getUserTimezoneChanges.METADATA,
    template: getUserTimezoneChanges.METADATA.path,
    path: getUserTimezoneChanges.path(),
  });
}
export namespace getUserTimezoneChanges {
  export type Output = {
    id: string;
    userId: string;
    ianaTimezone: string;
    changesAt: string & tags.Format<"date-time">;
    cityLabel: null | string;
    countryLabel: null | string;
    deviceId: null | string;
  }[];

  export const METADATA = {
    method: "GET",
    path: "/timezone-change",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/timezone-change";
}

/**
 * @controller TimezoneChangeController.createTimezoneChange
 * @path PUT /timezone-change
 * @accessor api.functional.timezone_change.createTimezoneChange
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createTimezoneChange(
  connection: IConnection,
  createTimezoneChangeDto: createTimezoneChange.Body,
): Promise<createTimezoneChange.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createTimezoneChange.METADATA,
      template: createTimezoneChange.METADATA.path,
      path: createTimezoneChange.path(),
    },
    createTimezoneChangeDto,
  );
}
export namespace createTimezoneChange {
  export type Body = CreateTimezoneChangeDto;
  export type Output = {
    id: string;
    userId: string;
    ianaTimezone: string;
    changesAt: string & tags.Format<"date-time">;
    cityLabel: null | string;
    countryLabel: null | string;
    deviceId: null | string;
  };

  export const METADATA = {
    method: "PUT",
    path: "/timezone-change",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/timezone-change";
}

/**
 * @controller TimezoneChangeController.updateTimezoneChange
 * @path PATCH /timezone-change
 * @accessor api.functional.timezone_change.updateTimezoneChange
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateTimezoneChange(
  connection: IConnection,
  updateTimezoneChangeDto: updateTimezoneChange.Body,
): Promise<updateTimezoneChange.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateTimezoneChange.METADATA,
      template: updateTimezoneChange.METADATA.path,
      path: updateTimezoneChange.path(),
    },
    updateTimezoneChangeDto,
  );
}
export namespace updateTimezoneChange {
  export type Body = UpdateTimezoneChangeDto;
  export type Output = {
    id: string;
    userId: string;
    ianaTimezone: string;
    changesAt: string & tags.Format<"date-time">;
    cityLabel: null | string;
    countryLabel: null | string;
    deviceId: null | string;
  };

  export const METADATA = {
    method: "PATCH",
    path: "/timezone-change",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/timezone-change";
}
