/**
 * @packageDocumentation
 * @module api.functional.event
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { CreateEventDto } from "../../structures/CreateEventDto";
import type { EventRangeQuery } from "../../structures/EventRangeQuery";
import type { UpdateEventDto } from "../../structures/UpdateEventDto";

export * as by_project from "./by_project/index";

/**
 * @controller EventsController.getEventsInRange
 * @path GET /event
 * @accessor api.functional.event.getEventsInRange
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEventsInRange(
  connection: IConnection,
  query: getEventsInRange.Query,
): Promise<getEventsInRange.Output> {
  return PlainFetcher.fetch(connection, {
    ...getEventsInRange.METADATA,
    template: getEventsInRange.METADATA.path,
    path: getEventsInRange.path(query),
  });
}
export namespace getEventsInRange {
  export type Query = EventRangeQuery;
  export type Output = {
    id: string;
    projectId: string;
    recurringTimeComponentId: null | string;
    overridedName: null | string;
    overridedGoal: null | string;
    overridedContext: null | string;
    start: null | (string & tags.Format<"date-time">);
    end: null | (string & tags.Format<"date-time">);
    recurringOccurrenceIndex: null | number;
    recurringTimeSlotsId: null | string;
  }[];

  export const METADATA = {
    method: "GET",
    path: "/event",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/event";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}

/**
 * @controller EventsController.createEvent
 * @path POST /event
 * @accessor api.functional.event.createEvent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createEvent(
  connection: IConnection,
  body: createEvent.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createEvent.METADATA,
      template: createEvent.METADATA.path,
      path: createEvent.path(),
    },
    body,
  );
}
export namespace createEvent {
  export type Body = CreateEventDto;

  export const METADATA = {
    method: "POST",
    path: "/event",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/event";
}

/**
 * @controller EventsController.updateEvent
 * @path PATCH /event
 * @accessor api.functional.event.updateEvent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateEvent(
  connection: IConnection,
  body: updateEvent.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateEvent.METADATA,
      template: updateEvent.METADATA.path,
      path: updateEvent.path(),
    },
    body,
  );
}
export namespace updateEvent {
  export type Body = UpdateEventDto;

  export const METADATA = {
    method: "PATCH",
    path: "/event",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/event";
}

/**
 * @controller EventsController.deleteEvent
 * @path DELETE /event
 * @accessor api.functional.event.deleteEvent
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteEvent(
  connection: IConnection,
  query: deleteEvent.Query,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteEvent.METADATA,
    template: deleteEvent.METADATA.path,
    path: deleteEvent.path(query),
  });
}
export namespace deleteEvent {
  export type Query = {
    id: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/event",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/event";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
