/**
 * @packageDocumentation
 * @module api.functional.project
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { CreateProjectDto } from "../../structures/CreateProjectDto";
import type { ProjectWithTimeSlots } from "../../structures/ProjectWithTimeSlots";
import type { UpdateProjectDto } from "../../structures/UpdateProjectDto";

export * as colors from "./colors/index";
export * as move from "./move/index";

/**
 * @controller ProjectsController.getProjectsByUser
 * @path GET /project
 * @accessor api.functional.project.getProjectsByUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getProjectsByUser(
  connection: IConnection,
): Promise<getProjectsByUser.Output> {
  return PlainFetcher.fetch(connection, {
    ...getProjectsByUser.METADATA,
    template: getProjectsByUser.METADATA.path,
    path: getProjectsByUser.path(),
  });
}
export namespace getProjectsByUser {
  export type Output = ProjectWithTimeSlots[];

  export const METADATA = {
    method: "GET",
    path: "/project",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/project";
}

/**
 * @controller ProjectsController.createProject
 * @path POST /project
 * @accessor api.functional.project.createProject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createProject(
  connection: IConnection,
  body: createProject.Body,
): Promise<createProject.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createProject.METADATA,
      template: createProject.METADATA.path,
      path: createProject.path(),
    },
    body,
  );
}
export namespace createProject {
  export type Body = CreateProjectDto;
  export type Output = ProjectWithTimeSlots;

  export const METADATA = {
    method: "POST",
    path: "/project",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/project";
}

/**
 * @controller ProjectsController.updateProject
 * @path PATCH /project
 * @accessor api.functional.project.updateProject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateProject(
  connection: IConnection,
  body: updateProject.Body,
): Promise<updateProject.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...updateProject.METADATA,
      template: updateProject.METADATA.path,
      path: updateProject.path(),
    },
    body,
  );
}
export namespace updateProject {
  export type Body = UpdateProjectDto;
  export type Output = ProjectWithTimeSlots;

  export const METADATA = {
    method: "PATCH",
    path: "/project",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/project";
}

/**
 * @controller ProjectsController.deleteProject
 * @path DELETE /project
 * @accessor api.functional.project.deleteProject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteProject(
  connection: IConnection,
  query: deleteProject.Query,
): Promise<void> {
  return PlainFetcher.fetch(connection, {
    ...deleteProject.METADATA,
    template: deleteProject.METADATA.path,
    path: deleteProject.path(query),
  });
}
export namespace deleteProject {
  export type Query = {
    id: string;
  };

  export const METADATA = {
    method: "DELETE",
    path: "/project",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/project";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
