/**
 * @packageDocumentation
 * @module api.functional.event.by_project
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { ProjectEventsQuery } from "../../../structures/ProjectEventsQuery";

/**
 * @controller EventsController.getEventsOfProject
 * @path GET /event/by-project
 * @accessor api.functional.event.by_project.getEventsOfProject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getEventsOfProject(
  connection: IConnection,
  query: getEventsOfProject.Query,
): Promise<getEventsOfProject.Output> {
  return PlainFetcher.fetch(connection, {
    ...getEventsOfProject.METADATA,
    template: getEventsOfProject.METADATA.path,
    path: getEventsOfProject.path(query),
  });
}
export namespace getEventsOfProject {
  export type Query = ProjectEventsQuery;
  export type Output = {
    id: string;
    projectId: string;
    recurringTimeComponentId: null | string;
    overridedName: null | string;
    overridedGoal: null | string;
    overridedContext: null | string;
    start: null | (string & tags.Format<"date-time">);
    end: null | (string & tags.Format<"date-time">);
    recurringOccurrenceIndex: null | number;
    recurringTimeSlotsId: null | string;
  }[];

  export const METADATA = {
    method: "GET",
    path: "/event/by-project",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = (query: Query) => {
    const variables: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(query as any))
      if (undefined === value) continue;
      else if (Array.isArray(value))
        value.forEach((elem: any) => variables.append(key, String(elem)));
      else variables.set(key, String(value));
    const location: string = "/event/by-project";
    return 0 === variables.size
      ? location
      : `${location}?${variables.toString()}`;
  };
}
