/**
 * @packageDocumentation
 * @module api.functional.project.move
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

import type { MoveProjectDto } from "../../../structures/MoveProjectDto";

/**
 * @controller ProjectsController.moveProject
 * @path POST /project/move
 * @accessor api.functional.project.move.moveProject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function moveProject(
  connection: IConnection,
  body: moveProject.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...moveProject.METADATA,
      template: moveProject.METADATA.path,
      path: moveProject.path(),
    },
    body,
  );
}
export namespace moveProject {
  export type Body = MoveProjectDto;

  export const METADATA = {
    method: "POST",
    path: "/project/move",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/project/move";
}
