/**
 * @packageDocumentation
 * @module api.functional.project.move
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";
import type { tags } from "typia";

import type { MoveProjectDto } from "../../../structures/MoveProjectDto";

/**
 * @controller ProjectsController.moveProject
 * @path POST /project/move
 * @accessor api.functional.project.move.moveProject
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function moveProject(
  connection: IConnection,
  body: moveProject.Body,
): Promise<moveProject.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...moveProject.METADATA,
      template: moveProject.METADATA.path,
      path: moveProject.path(),
    },
    body,
  );
}
export namespace moveProject {
  export type Body = MoveProjectDto;
  export type Output = {
    name: null | string;
    id: string;
    goal: null | string;
    context: null | string;
    timeNeededMinutes: null | number;
    minBlockMinutes: null | number;
    repetitionsNeeded: null | number;
    earliestDate: null | (string & tags.Format<"date-time">);
    earliestTime: null | (string & tags.Format<"date-time">);
    deadlineDate: null | (string & tags.Format<"date-time">);
    deadlineTime: null | (string & tags.Format<"date-time">);
    projectStatus: "ACTIVE" | "BACKLOG";
    flexibleTimezone: boolean;
    originalTimezone: null | string;
    position: string;
    parentProjectId: null | string;
    colorId: null | string;
    userId: string;
  }[];

  export const METADATA = {
    method: "POST",
    path: "/project/move",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/project/move";
}
