/**
 * @packageDocumentation
 * @module api.functional.user
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher";

/**
 * @controller UserController.getCurrentUser
 * @path GET /user
 * @accessor api.functional.user.getCurrentUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCurrentUser(
  connection: IConnection,
): Promise<getCurrentUser.Output> {
  return PlainFetcher.fetch(connection, {
    ...getCurrentUser.METADATA,
    template: getCurrentUser.METADATA.path,
    path: getCurrentUser.path(),
  });
}
export namespace getCurrentUser {
  export type Output = {
    username: string;
    id: string;
    defaultEvenLengthMinutes: number;
    projectsVersion: number;
  };

  export const METADATA = {
    method: "GET",
    path: "/user",
    request: null,
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 200,
  } as const;

  export const path = () => "/user";
}

/**
 * @controller UserController.createUser
 * @path POST /user
 * @accessor api.functional.user.createUser
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function createUser(
  connection: IConnection,
  body: createUser.Body,
): Promise<void> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...createUser.METADATA,
      template: createUser.METADATA.path,
      path: createUser.path(),
    },
    body,
  );
}
export namespace createUser {
  export type Body = {
    username: string;
    password: string;
  };

  export const METADATA = {
    method: "POST",
    path: "/user",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: 201,
  } as const;

  export const path = () => "/user";
}
